# Generated by Django 5.2.7 on 2025-11-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_questionaire_question_questionaire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answers",
            name="response",
        ),
    ]
