# Generated by Django 5.2.7 on 2025-11-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_answers_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='response',
            field=models.BigIntegerField(null=True),
        ),
    ]
