# Generated by Django 5.2.7 on 2025-11-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_answers_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.person'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_a', to='core.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_b', to='core.person')),
            ],
        ),
    ]
